package carfinance.api;

import java.util.Map;
import java.util.Set;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import carfinance.server.responseGenerator.OptionsCollector;
import carfinance.server.responseGenerator.Response;
import carfinance.server.responseGenerator.ResponseGenerator;
import carfinance.server.offerGenerator.Catalogue;
import carfinance.server.offerGenerator.OfferGenerator;
import carfinance.server.preprocessor.Validator;
import carfinance.server.calculator.InterestRateRegulator;

/**
 * @author jeanniehe
 * The Rest Api corresponding for enabling communication between 
 * the client and the server.
 */
@RestController
@CrossOrigin
public class CalculatorRestController {
	
	private OptionsCollector optionsCollector;
	private Validator validator;
	private OfferGenerator offerGenerator;
	
	/**
	 * The default constructor creating default server objects as 
	 * instance variables to use in this rest controller.
	 */
	public CalculatorRestController() {
		Catalogue catalogue = new Catalogue();
		InterestRateRegulator interestRateRegulator = new InterestRateRegulator();
		
		optionsCollector = new OptionsCollector(catalogue, interestRateRegulator);
		validator = new Validator(catalogue, interestRateRegulator);
		offerGenerator = new OfferGenerator(catalogue, interestRateRegulator);
	}
	
	
	/**
	 * Enables communication between clients and the option collector 
	 * through a GET request.
	 * @return a map of categorical input options required by the server.
	 */
	@GetMapping("/car-finance")
	public Map<String, Set<String>> getOptions() {
		return optionsCollector.getOptions();
	}
	
	
	/**
	 * Enables communication between clients and the response generator 
	 * through a GET request.
	 * @param a dictionary mapping field names to users inputs.
	 * @return a response generated by the response generator.
	 */
	@GetMapping("/car-finance/get-offers")
	public Response getResponse(@RequestParam Map<String,String> userInputs){
		return ResponseGenerator.generateResponse(userInputs, validator, offerGenerator);
	}
}
