package carfinance.server.responseGenerator;

import carfinance.server.offerGenerator.Offer;
import carfinance.server.preprocessor.AnswerSheet;

/**
 * An extended version of response allowing one to include a list of 
 * offers along with an auto-generated message.
 */
public class ResponseWithOffer extends Response{
	private Offer[] offers;
	
	/**
	 * The constructor inherited from the parent class
	 */
	public ResponseWithOffer(AnswerSheet answerSheet, String string) {
		super(answerSheet, string);
	}
	
	/**
	 * An extended constructor to allow the creation of a response with offers.
	 */
	public ResponseWithOffer(AnswerSheet answersheet, Offer[] offers) {
		// Step 1: store the answer sheet and an auto generated message as in the parent class
		super(answersheet, generateCongratMessage(offers.length, answersheet));
		// Step 2: store offers
		this.offers = offers;
	}
	
	/**
	 * A method to generate the congratulation message to the user.
	 * @param numOfOffers: the number of offers generated by the server.
	 * @param answersheet: the answer sheet as a parsed version of the user's inputs.
	 * @return a congratulation message to the user.
	 */
	private static String generateCongratMessage(int numOfOffers, AnswerSheet answersheet) {
		String carType = answersheet.getCarType();
		String channel = answersheet.getChannel();
		
		return String.format("Congratulations! You've got %d offer%s "
				+ " The interest rate is calculated for your purchase of %s %s %s-based car as %s %s. The annual payment%s generated "
				+ "based on that interest rate along with your loan term and loan amount after down payment.",
				numOfOffers,
				numOfOffers < 2 ? "!" : "s! The offers are sorted in increasing order by our recommendation.",
				GrammarHelper.getArticle(carType), carType.toLowerCase().replace("_", " "), answersheet.getFuelType().toLowerCase(), 
				GrammarHelper.getArticle(channel), channel.toLowerCase().replace("_", " "), numOfOffers == 1 ? " is":"s are");
	}
	
	/**
	 * A method to allow retrieval of offers.
	 * @return the list of offers
	 */
	public Offer[] getOffers(){
		return this.offers;
	}
	
}
