CREATE DATABASE CarFinance

USE CarFinance


CREATE TABLE Catalogue
(
  ProductID INT  NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20)  NOT NULL, 
  ChannelID INT REFERENCES  NOT NULL,
  InterestRate FLOAT(4,2) NOT NULL,  
  PRIMARY KEY (ProductID),
  FOREIGN KEY (ChannelID) REFERENCES Channels(ChannelID)
)

CREATE TABLE Channels
(
  ChannelID INT  NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20)  NOT NULL,
  PRIMARY KEY (ChannelID)
)




